actions:
  - type: remove
    selector: "footer"
  - type: replace
    selector: "#old-header"
    newElement: "<header id='new-header' class='header'>Updated Header Content</header>"
  - type: insert
    position: "before"
    target: "body"
    element: "<aside class='sidebar'>Sidebar Content</aside>"
  - type: alter
    oldValue: "Welcome"
    newValue: "Greetings (alter phase)"
